spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 24b06706c51e89bf2b31
            clientSecret: 6993ecce15c2b148fa62bf2567eed81f386538cc
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user