
# 주석 처리된건 배포할경우 코드
#server:
#  port: 5000
#spring:
#  jpa:
#    database: MYSQL
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
#    username: ${rds.username}
#    password: ${rds.password}

server:
  port: 8080
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password: '0000'
